version: 2.1

jobs:
  build-and-release:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2026.10
    steps:
      - checkout
      - run:
          name: docker-deploy
          command: sh ./docker-release.sh

workflows:
  build:
    jobs:
      - build-and-release:
          filters:
            branches:
              only:
                - main
